# Cleaning webscraped data
In this notebook we shall clean and derive some simple statistics from the webscraped data from [giving.sg](https://www.giving.sg/) <br>

# Contents
[Basic Cleaning](#Basic-Cleaning)<br>
[Organisation](#Organisation) <br>
[Event Name](#Event-Name) <br>
[DayDate](#DayDate) <br>
[Duration](#Duration)<br>
[Location](#Location)<br>
[Causes](#Causes)<br>
[Skills](#Skills)<br>
[Suitability](#Suitability)<br>
[Min Age](#Min-Age)<br>

[Cleaned Data](#Cleaned-Data) $\Leftarrow$ Go Straight to here for cleaned data <br>

# Basic Cleaning
[Back to Contents](#Contents)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def convert_location_cell(cell):
    assert (type(cell) == str),"Location cell should be type str"
    return cell.split('\n')[0]

In [3]:
df = pd.read_excel('givingsg.xlsx', na_values= ['null', 'NA'], converters={
    'Location':convert_location_cell
})

df.drop(['web-scraper-order', 'web-scraper-start-url', 'EventID', 'EventID-href'], 
        axis = 1, 
        inplace = True)
df.head()

,Organisation,Event Name,DayDate,Duration,Location,Cause1,Cause2,Cause3,Skills,Suitability,Min Age
0,AWWA Ltd,Lunch Assistant for Seniors,"Thu, 11 Jan 2018 to Sat, 31 Mar 2018",Few hours a week on weekday,Ang Mo Kio,Elderly,Health,NaN,Skills required: No Specific Skills Required,"Suitable for: First Timers, Seniors, Open to All",Min. age: 18
1,St Luke's Hospital,Volunteering Opportunities,"Tue, 16 Jan 2018 to Fri, 21 Dec 2018",Flexible on weekday,Bukit Batok,Community,Disability,Elderly,"Skills required: Volunteer Management, Other S...",Suitable for: Open to All,Min. age: 18
2,South Central Community Family Service Centre ...,Adhoc Volunteering - Chinese New Year Celebrat...,"Sat, 24 Feb 2018",1:00 PM TO 7:00 PM (6.0 hours),River Valley,Children & Youth,Community,Elderly,Skills required: No Specific Skills Required,"Suitable for: First Timers, Open to All",Min. age: 16
3,Shan You,A Good Day Out by Tote Board,"Sat, 10 Feb 2018\n \n\t ...",9:30 AM TO 3:00 PM (5.5 hours),Downtown Core,Community,Elderly,Social Service,Skills required: Other Skills,"Suitable for: Seniors, Open to All",Min. age: 16
4,Students Care Service,Engage children and youths at SCS!,"Tue, 2 Jan 2018 to Mon, 31 Dec 2018",Flexible on weekday or weekend,Hougang,Children & Youth,Education,Families,NaN,NaN,NaN

# Organisation
[Back to Contents](#Contents)

# Event Name
[Back to Contents](#Contents)

# DayDate
[Back to Contents](#Contents)

In [4]:
def split_dayDate():
    pass

# print(df["DayDate"])
def create_dueDate():
    dueDate = []
    for i in range(len(df["DayDate"])):
#         temp = df["DayDate"][i].split('\n')[0]
        temp = df["DayDate"][i].split('\n')[0].split(', ')[1:][-1]
        dueDate.append(temp)
    df['DueDate'] = pd.Series(dueDate)
    
create_dueDate()

# Duration
[Back to Contents](#Contents)

In [36]:
df["Duration"].describe()

count                             139
unique                             66
top       Few hours a week on weekday
freq                               16
Name: Duration, dtype: object

In [35]:
for i in df["Duration"]:
    print(i)

Few hours a week on weekday
Flexible on weekday
1:00 PM TO 7:00 PM (6.0 hours)
9:30 AM TO 3:00 PM (5.5 hours)
Flexible on weekday or weekend
10:00 AM TO 1:00 PM (3.0 hours)
9:00 AM TO 11:30 AM (2.5 hours)
2:00 PM TO 4:30 PM (2.5 hours)
3:00 PM TO 5:00 PM (2.0 hours)
2 to 3 days per week on weekday
1:30 PM TO 4:30 PM (3.0 hours)
Few hours a week on weekday
6:30 AM TO 12:00 PM (5.5 hours)
7:30 AM TO 2:00 PM (6.5 hours)
9:00 AM TO 2:00 PM (5.0 hours)
7:00 PM TO 9:00 PM (2.0 hours)
10:00 AM TO 12:00 PM (2.0 hours)
8:00 AM TO 6:00 PM (10.0 hours)
Flexible on weekday or weekend
Flexible on weekday or weekend
Flexible on weekday or weekend
2:00 PM TO 4:30 PM (2.5 hours)
7:30 PM TO 9:30 PM (2.0 hours)
7:00 PM TO 9:00 PM (2.0 hours)
9:00 AM TO 1:00 PM (4.0 hours)
4:00 PM TO 11:00 PM (7.0 hours)
7:00 PM TO 9:00 PM (2.0 hours)
7:30 PM TO 9:30 PM (2.0 hours)
9:30 AM TO 11:00 AM (289.5 hours)
9:30 AM TO 11:00 AM (289.5 hours)
7:30 PM TO 9:30 PM (2.0 hours)
7:30 PM TO 9:30 PM (2.0 hours)
9:00 AM TO 12:30 PM (3.5 hours)
10:00 AM TO 12:30 PM (2.5 hours)
10:30 AM TO 4:30 PM (6.0 hours)
11:00 AM TO 3:00 PM (4.0 hours)
10:00 AM TO 1:00 PM (3.0 hours)
1 day per week on weekday
Few hours a week on weekday or weekend
6:00 PM TO 9:30 PM (3.5 hours)
1 day per week on weekday
8:30 AM TO 1:30 PM (5.0 hours)
Flexible on weekday or weekend
8:30 AM TO 1:30 PM (5.0 hours)
9:00 AM TO 1:00 PM (4.0 hours)
8:30 AM TO 12:30 PM (4.0 hours)
Flexible on weekday
9:00 AM TO 12:30 PM (3.5 hours)
Flexible on weekday or weekend
2:00 PM TO 4:30 PM (2.5 hours)
1:00 PM TO 4:30 PM (3.5 hours)
1:00 PM TO 4:30 PM (3.5 hours)
Few hours a week on weekday
1:30 PM TO 4:30 PM (3.0 hours)
9:30 AM TO 12:30 PM (3.0 hours)
10:00 AM TO 11:30 AM (1.5 hour)
9:00 AM TO 6:00 PM (81.0 hours)
2:00 PM TO 7:00 PM (5.0 hours)
Few hours a week on weekday
6:30 AM TO 5:00 PM (10.5 hours)
7:00 PM TO 9:00 PM (2.0 hours)
Few hours a week on weekday
9:30 AM TO 12:30 PM (3.0 hours)
Flexible on weekday or weekend
2:00 PM TO 5:00 PM (3.0 hours)
2 to 3 days per week on weekday
12:00 AM TO 11:30 PM (119.5 hours)
2 to 3 days per week on weekday
3:00 PM TO 4:30 PM (1.5 hour)
2 to 3 days per week on weekday
Flexible on weekday or weekend
7:00 AM TO 8:00 PM (133.0 hours)
7:30 AM TO 11:00 AM (3.5 hours)
1 day per week on weekday
Few hours a week on weekday
2:00 PM TO 5:00 PM (3.0 hours)
10:30 AM TO 12:30 PM (2.0 hours)
8:30 AM TO 2:30 PM (6.0 hours)
6:00 AM TO 10:00 AM (4.0 hours)
7:00 AM TO 4:00 PM (201.0 hours)
11:00 PM TO 6:00 AM (7.0 hours)
Few hours a week on weekday
9:00 AM TO 2:00 PM (5.0 hours)
2:00 PM TO 5:00 PM (3.0 hours)
2:00 PM TO 5:00 PM (3.0 hours)
10:00 AM TO 4:00 PM (6.0 hours)
7:00 PM TO 9:00 PM (2.0 hours)
1 day per week on weekday
9:30 AM TO 12:30 PM (3.0 hours)
6:30 AM TO 3:00 PM (8.5 hours)
9:00 AM TO 4:00 PM (7.0 hours)
Few hours a week on weekday
Few hours a week on weekday
2 to 3 days per week on weekday
8:00 AM TO 12:00 PM (4.0 hours)
1 day per week on weekday or weekend
7:30 AM TO 1:00 PM (5.5 hours)
1 day per week on weekday or weekend
Few hours a week on weekend
9:00 AM TO 1:00 PM (4.0 hours)
Few hours a week on weekday
8:30 AM TO 12:30 PM (4.0 hours)
2 to 3 days per week on weekday
6:30 PM TO 9:30 PM (3.0 hours)
1 day per week on weekday
10:30 AM TO 1:00 PM (2.5 hours)
2:00 PM TO 3:30 PM (1.5 hour)
Few hours a week on weekday
2:00 PM TO 5:00 PM (3.0 hours)
Flexible on weekday or weekend
12:00 PM TO 3:00 PM (3.0 hours)
Few hours a week on weekday
Flexible on weekday or weekend
2:00 PM TO 4:30 PM (2.5 hours)
3:00 PM TO 4:30 PM (1.5 hour)
8:30 AM TO 1:30 PM (5.0 hours)
Few hours a week on weekday
Flexible on weekday or weekend
Few hours a week on weekend
3:00 PM TO 4:30 PM (385.5 hours)
2:00 PM TO 5:00 PM (3.0 hours)
1 day per week on weekday
Flexible on weekday or weekend
10:00 AM TO 5:00 PM (7.0 hours)
3:00 PM TO 4:00 PM (1.0 hour)
Few hours a week on weekday
Few hours a week on weekday
12:30 PM TO 4:30 PM (4.0 hours)
Few hours a week on weekday
2 to 3 days per week on weekday
1:30 PM TO 3:00 PM (1.5 hour)
Flexible on weekday or weekend
Few hours a week on weekday or weekend
2:00 PM TO 6:00 PM (4.0 hours)
1 day per week on weekday
8:00 AM TO 4:00 PM (8.0 hours)
12:00 PM TO 3:00 PM (3.0 hours)
1 day per week on weekend
7:00 PM TO 10:00 PM (3.0 hours)

# Location
[Back to Contents](#Contents)

In [ ]:
def convert_location_cell(cell):
    assert (type(cell) == str),"Location cell should be type str"
    return cell.split('\n')[0]

# Causes
[Back to Contents](#Contents)

In [43]:
print(df["Cause1"].describe())
print("=======================")
print(df["Cause2"].describe())
print("=======================")
print(df["Cause3"].describe())

count           136
unique            7
top       Community
freq             63
Name: Cause1, dtype: object
=======================
count         104
unique          9
top       Elderly
freq           38
Name: Cause2, dtype: object
=======================
count                 90
unique                 8
top       Social Service
freq                  23
Name: Cause3, dtype: object

In [46]:
print(df["Cause1"].value_counts())
print('============================')
print(df["Cause2"].value_counts())
print('============================')
print(df["Cause3"].value_counts())

Community           63
Children & Youth    38
Elderly             19
Disability           8
Social Service       5
Arts & Heritage      2
Families             1
Name: Cause1, dtype: int64
============================
Elderly           38
Community         28
Disability        13
Education          6
Health             6
Families           5
Social Service     3
Environment        3
Sports             2
Name: Cause2, dtype: int64
============================
Social Service    23
Health            21
Elderly           16
Families          14
Education         10
Humanitarian       3
Environment        2
Disability         1
Name: Cause3, dtype: int64

In [38]:
for i in df["Cause1"]:
    print(i)

Elderly
Community
Children & Youth
Community
Children & Youth
Community
Community
Community
Elderly
Community
Community
Community
Children & Youth
Community
Children & Youth
Social Service
Community
Disability
Community
Community
Disability
Community
Elderly
Social Service
Community
Community
Social Service
Elderly
Disability
Disability
Elderly
Elderly
Community
Children & Youth
Elderly
Children & Youth
Children & Youth
Community
Community
Children & Youth
Arts & Heritage
Community
Community
Community
Elderly
Community
Community
Community
Community
Community
Community
Community
Families
Elderly
Disability
Elderly
Children & Youth
Children & Youth
Community
Children & Youth
Social Service
Elderly
Children & Youth
Community
Community
Community
nan
Community
Community
Children & Youth
Community
Disability
Community
Arts & Heritage
Children & Youth
Elderly
Community
Disability
Community
Children & Youth
Community
Children & Youth
Children & Youth
Elderly
Elderly
Community
Social Service
Community
Community
Children & Youth
Disability
Elderly
Children & Youth
Community
Children & Youth
Community
Children & Youth
Children & Youth
Children & Youth
Children & Youth
Children & Youth
Community
Community
Children & Youth
Community
Community
Children & Youth
Children & Youth
Elderly
Community
Community
Children & Youth
Community
Community
Community
Community
Community
Community
Children & Youth
nan
Children & Youth
Children & Youth
Children & Youth
Community
Children & Youth
Elderly
Elderly
Children & Youth
Elderly
Community
Community
Community
Community
Children & Youth
Community
nan
Community
Children & Youth
Children & Youth

In [47]:
for i in df["Cause2"]:
    print(i)

Health
Disability
Community
Elderly
Education
Disability
Elderly
Elderly
Social Service
Environment
Disability
Elderly
Community
Health
Community
nan
Elderly
Sports
Elderly
Elderly
Elderly
Elderly
nan
nan
Elderly
Health
nan
nan
nan
nan
nan
nan
Elderly
Community
nan
Community
Environment
Elderly
Social Service
Community
Community
Disability
Elderly
Disability
nan
Elderly
Families
Elderly
Elderly
Elderly
Disability
Elderly
nan
nan
Social Service
nan
Community
Community
Elderly
Community
nan
Health
Community
Disability
Disability
Disability
nan
Elderly
Elderly
Community
Elderly
Sports
Elderly
Community
Community
nan
Elderly
nan
Health
Community
Health
Community
Community
nan
nan
Education
nan
Families
Disability
Community
nan
nan
nan
Elderly
Education
Elderly
Disability
nan
Community
Community
nan
Elderly
Education
Families
Elderly
Disability
Community
nan
nan
Environment
Elderly
Community
Elderly
Elderly
Elderly
Elderly
Education
Disability
Community
nan
Community
Community
Families
Education
nan
nan
nan
nan
nan
Elderly
Elderly
Elderly
Elderly
Community
Families
nan
Elderly
Community
Community

In [48]:
for i in df["Cause3"]:
    print(i)

nan
Elderly
Elderly
Social Service
Families
Elderly
Health
Health
nan
Health
Elderly
Health
Elderly
Humanitarian
Education
nan
Health
nan
nan
Social Service
Health
Health
nan
nan
Families
Social Service
nan
nan
nan
nan
nan
nan
Social Service
Elderly
nan
Elderly
Social Service
Families
nan
Elderly
Social Service
Elderly
Social Service
nan
nan
Social Service
Health
Social Service
Social Service
Health
Families
Health
nan
nan
nan
nan
Humanitarian
Education
nan
Elderly
nan
nan
Families
Humanitarian
Social Service
Elderly
nan
Social Service
Health
Education
Health
nan
nan
Education
Education
nan
Social Service
nan
Social Service
Education
Social Service
Families
Elderly
nan
nan
Environment
nan
Health
Health
Elderly
nan
nan
nan
Families
Families
Social Service
Elderly
nan
Education
Families
nan
Social Service
Health
nan
Families
Families
Education
nan
nan
nan
Health
Families
Social Service
Health
nan
Social Service
Elderly
Elderly
Education
nan
Disability
Social Service
Social Service
Environment
nan
nan
nan
nan
nan
Families
Health
Social Service
Health
Social Service
Health
nan
Health
Education
Families

# Skills
[Back to Contents](#Contents)

In [ ]:
df.info()

In [5]:
# Execute this first
def clean_skills():
    for i in range(len(df["Skills"])):
        if type(df["Skills"][i]) != str:
            continue
        df["Skills"][i] = df["Skills"][i].split(': ')[1:][0]
clean_skills()

In [30]:
# Execute this second
def clean_skills1():
    for i in range(len(df['Skills'])):
        if type(df['Skills'][i]) != str:
            df['Skills'][i] = [df['Skills'][i]]
            continue
        df['Skills'][i] = df['Skills'][i].split(',')
clean_skills1()

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [31]:
df['Skills']

0                          [No Specific Skills Required]
1                  [Volunteer Management,  Other Skills]
2                          [No Specific Skills Required]
3                                         [Other Skills]
4                                                  [nan]
5                          [No Specific Skills Required]
6                          [No Specific Skills Required]
7                          [No Specific Skills Required]
8                          [No Specific Skills Required]
9                          [No Specific Skills Required]
10                         [No Specific Skills Required]
11                         [No Specific Skills Required]
12                                         [Fundraising]
13                         [No Specific Skills Required]
14                         [No Specific Skills Required]
15                                                 [nan]
16                         [No Specific Skills Required]
17                                                 [nan]
18                         [No Specific Skills Required]
19     [Arts & Music,  Counselling & Mentoring,  Othe...
20                         [No Specific Skills Required]
21                         [No Specific Skills Required]
22                                        [Other Skills]
23                                                 [nan]
24                         [No Specific Skills Required]
25                         [No Specific Skills Required]
26                                                 [nan]
27                         [No Specific Skills Required]
28                         [No Specific Skills Required]
29                         [No Specific Skills Required]
                             ...
109                                                [nan]
110                        [No Specific Skills Required]
111                 [Coaching & Training,  Other Skills]
112                                                [nan]
113                        [No Specific Skills Required]
114                        [No Specific Skills Required]
115                        [No Specific Skills Required]
116                        [No Specific Skills Required]
117                        [No Specific Skills Required]
118                        [No Specific Skills Required]
119                        [No Specific Skills Required]
120                        [No Specific Skills Required]
121                        [No Specific Skills Required]
122                        [No Specific Skills Required]
123                                                [nan]
124                        [No Specific Skills Required]
125                        [No Specific Skills Required]
126                        [No Specific Skills Required]
127                                       [Other Skills]
128                        [No Specific Skills Required]
129                                                [nan]
130                        [No Specific Skills Required]
131    [Arts & Music,  Counselling & Mentoring,  Medi...
132                        [No Specific Skills Required]
133                        [No Specific Skills Required]
134                                       [Arts & Music]
135                                        [Fundraising]
136                        [No Specific Skills Required]
137                        [No Specific Skills Required]
138                                       [Other Skills]
Name: Skills, Length: 139, dtype: object

# Suitability
[Back to Contents](#Contents)

In [6]:
def clean_suitability():
    for i in range(len(df["Suitability"])):
        if type(df["Suitability"][i]) != str:
            continue
        df["Suitability"][i] = df["Suitability"][i].split(': ')[1:][0]
clean_suitability()

# Min Age
[Back to Contents](#Contents)

In [7]:
def clean_minAge():
    for i in range(len(df["Min Age"])):
        if type(df["Min Age"][i]) != str:
            continue
#         print(i)
        df["Min Age"][i] = df["Min Age"][i].split(': ')[1]
clean_minAge()

# Saving the Cleaned Data

In [8]:
df.drop(['DayDate'], axis = 1, inplace = True)

In [9]:
df.head()

,Organisation,Event Name,Duration,Location,Cause1,Cause2,Cause3,Skills,Suitability,Min Age,DueDate
0,AWWA Ltd,Lunch Assistant for Seniors,Few hours a week on weekday,Ang Mo Kio,Elderly,Health,NaN,No Specific Skills Required,"First Timers, Seniors, Open to All",18,31 Mar 2018
1,St Luke's Hospital,Volunteering Opportunities,Flexible on weekday,Bukit Batok,Community,Disability,Elderly,"Volunteer Management, Other Skills",Open to All,18,21 Dec 2018
2,South Central Community Family Service Centre ...,Adhoc Volunteering - Chinese New Year Celebrat...,1:00 PM TO 7:00 PM (6.0 hours),River Valley,Children & Youth,Community,Elderly,No Specific Skills Required,"First Timers, Open to All",16,24 Feb 2018
3,Shan You,A Good Day Out by Tote Board,9:30 AM TO 3:00 PM (5.5 hours),Downtown Core,Community,Elderly,Social Service,Other Skills,"Seniors, Open to All",16,10 Feb 2018
4,Students Care Service,Engage children and youths at SCS!,Flexible on weekday or weekend,Hougang,Children & Youth,Education,Families,NaN,NaN,NaN,31 Dec 2018

In [32]:
df.to_excel('new4.xlsx', index = False)

# Cleaned Data
[Back to Contents](#Contents)

In [50]:
def convert_location_cell(cell):
    assert (type(cell) == str),"Location cell should be type str"
    return cell.split('\n')[0]

df = pd.read_excel('latest.xlsx', sheetname= 'Sheet1', converters={
    'Location':convert_location_cell
})
df.head()

,Organisation,Event Name,Duration,Location,Cause1,Cause2,Cause3,Skills,Suitability,Min Age,DueDate
0,AWWA Ltd,Lunch Assistant for Seniors,Few hours a week on weekday,Ang Mo Kio,Elderly,Health,NaN,['No Specific Skills Required'],"First Timers, Seniors, Open to All",18.0,31 Mar 2018
1,St Luke's Hospital,Volunteering Opportunities,Flexible on weekday,Bukit Batok,Community,Disability,Elderly,"['Volunteer Management', ' Other Skills']",Open to All,18.0,21 Dec 2018
2,South Central Community Family Service Centre ...,Adhoc Volunteering - Chinese New Year Celebrat...,1:00 PM TO 7:00 PM (6.0 hours),River Valley,Children & Youth,Community,Elderly,['No Specific Skills Required'],"First Timers, Open to All",16.0,24 Feb 2018
3,Shan You,A Good Day Out by Tote Board,9:30 AM TO 3:00 PM (5.5 hours),Downtown Core,Community,Elderly,Social Service,['Other Skills'],"Seniors, Open to All",16.0,10 Feb 2018
4,Students Care Service,Engage children and youths at SCS!,Flexible on weekday or weekend,Hougang,Children & Youth,Education,Families,[nan],NaN,NaN,31 Dec 2018

In [12]:
df.columns

Index(['Organisation', 'Event Name', 'Duration', 'Location', 'Cause1',
       'Cause2', 'Cause3', 'Skills', 'Suitability', 'Min Age', 'DueDate'],
      dtype='object')

In [ ]:
print(df['Organisation'].describe())
series_Org = df['Organisation'].value_counts()
series_Org

In [ ]:
print(df['Event Name'].describe())
series_EventName = df['Event Name'].value_counts()
series_EventName

In [ ]:
df['DayDate']

In [ ]:
df = pd.read_excel('givingsg.xlsx', parse_dates= True)

In [ ]:
df.head()